### ISSUE TITLE
CLI does not automatically exit the process when finished

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-cli#182]
## Describe the bug / expected behavior
The CLI does not automatically exit the initialization process when everything is finished. Users have to manually control-D to exit. I vaguely recall that this was not the case before.

## What are the steps to reproduce?

1. `npx -p @brightlayer-ui/cli blui new react --name=font-audit`
2. I selected "Blank", and "yes" to both ESLint and Prettier

## Screenshots / Screen recording

This is 10 minutes after everything has been installed:

<img width="750" alt="image" src="https://github.com/etn-ccis/blui-cli/assets/8997218/6f3b8011-cf19-4a34-9f80-1fe30dbf1423">

## Your environment information

macOS 13.3.1

**Comment by JeffGreiner-eaton** [comment]
this is duplicate issue logged here https://github.com/etn-ccis/blui-cli/issues/136
